services:

  fastbot-ros2-real:
    build:
      context: .
      dockerfile: fastbot-ros2-real/Dockerfile

    container_name: fastbot-ros2-real
    network_mode: host
    ipc: host
    pid: host
    privileged: true
    restart: unless-stopped

    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
      - /dev/ttyACM0:/dev/ttyACM0

    volumes:
      - /home/fastbot/ros2_ws:/root/ros2_ws
      - /var/lib/theconstruct.rrl:/var/lib/theconstruct.rrl


    environment:
      - ROS_DOMAIN_ID=30
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - CYCLONEDDS_URI=file:///var/lib/theconstruct.rrl/cyclonedds_husarnet.xml

    stdin_open: true
    tty: true

    command: >
      bash -c "
      source /opt/ros/humble/setup.bash &&
      sleep infinity
      "



  fastbot-ros2-slam-real:
    build:
      context: .
      dockerfile: fastbot-ros2-slam-real/Dockerfile

    container_name: fastbot-ros2-slam-real
    network_mode: host
    ipc: host
    pid: host
    privileged: true
    restart: unless-stopped

    volumes:
      - /home/fastbot/ros2_ws:/root/ros2_ws
      - /var/lib/theconstruct.rrl:/var/lib/theconstruct.rrl


    environment:
      - ROS_DOMAIN_ID=30
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - CYCLONEDDS_URI=file:///var/lib/theconstruct.rrl/cyclonedds_husarnet.xml

    stdin_open: true
    tty: true

    command: >
      bash -c "
      source /opt/ros/humble/setup.bash &&
      sleep infinity
      "
