FROM nginx:alpine

COPY webpage/ /usr/share/nginx/html/
COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 80


# Copiar la web correcta del rosject
#COPY simulation/webpage https://i-0932d1623340ab90d.robotigniteacademy.com/36b4e344-3c21-42dd-9ba8-9aac4ae35f43/webpage/

